#!/bin/busybox sh
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys
/bin/busybox mount -t devtmpfs devtmpfs /dev
/mpc-abi
abi_status=$?
/mpc-gpu-kernel
gpu_status=$?
/bin/busybox echo "MPC_LINUX_EXIT=$abi_status"
/bin/busybox echo "MPC_GPU_KERNEL_EXIT=$gpu_status"
/bin/busybox poweroff -f
